# Generated by Django 5.1.6 on 2025-02-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_liked_movies_liked'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liked',
            table=None,
        ),
    ]
